CXX=g++
CXXFLAGS=-ggdb -w -Werror -Wall

all: part1 part2 part3 part4 part5

part1: part1.cc
	$(CXX) $(CXXFLAGS) part1.cc -o part1

part2: part2.cc
	$(CXX) $(CXXFLAGS) part2.cc -o part2

part3: part3.cc
	$(CXX) $(CXXFLAGS) part3.cc -o part3

part4: part4.cc
	$(CXX) $(CXXFLAGS) part4.cc -o part4

part5: part5.cc
	$(CXX) $(CXXFLAGS) part5.cc -o part5
clean:
	rm part1 part2 part3 part4 part5
